---

- name: install package
  package:
    name: "{{ postfix_packages }}"
    state: present
  tags:
    - postfix
    - postfix_install

- name: Detect installed Postfix version without Python
  raw: postconf mail_version | awk -F' = ' '{print $2}'
  register: postfix_version_parsed

- name: Display Postfix version
  debug:
    msg: "Postfix version is {{ postfix_version_parsed.stdout }}"
